// <auto-generated />
using System;
using GreenFactory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenFactory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608210420_SyncAndCreateSettings")]
    partial class SyncAndCreateSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GreenFactory.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("GreenFactory.Models.EnergyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarbonKgCO2e")
                        .HasColumnType("REAL");

                    b.Property<string>("MeterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("WaterM3")
                        .HasColumnType("REAL");

                    b.Property<double>("kWh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EnergyRecords");
                });

            modelBuilder.Entity("GreenFactory.Models.KpiTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EnergyTarget")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WaterTarget")
                        .HasColumnType("REAL");

                    b.Property<double>("WaterThreshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("KpiTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
